
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: velitasymomentos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./vendor/delight-im/auth/Database/MySQL.sql:/docker-entrypoint-initdb.d/01_auth.sql

volumes:
  db_data: